import type { DesktopEntry } from "./types";

// Mock desktop snapshot used in mock mode (browser dev, or Tauri unavailable).
// Modeled loosely after a real cluttered Windows desktop so the
// classification engine has realistic edge cases to work with:
// project prefixes, duplicate "- copy" files, final/dated versions,
// school folders, shortcuts, installers, and old files.

const DESKTOP_PATH = "C:\\Users\\User\\Desktop";

function entry(partial: Omit<DesktopEntry, "id" | "path" | "baseName">): DesktopEntry {
  const dot = partial.name.lastIndexOf(".");
  const baseName = partial.isDirectory || dot <= 0 ? partial.name : partial.name.slice(0, dot);
  return {
    ...partial,
    id: `mock-${partial.name}`,
    baseName,
    path: `${DESKTOP_PATH}\\${partial.name}`,
  };
}

const day = (offsetDays: number): string => {
  const d = new Date();
  d.setDate(d.getDate() - offsetDays);
  return d.toISOString();
};

export const MOCK_DESKTOP_ENTRIES: DesktopEntry[] = [
  entry({ name: "컴프2.pdf", extension: "pdf", isDirectory: false, isShortcut: false, sizeBytes: 842_000, modifiedAt: day(400) }),
  entry({ name: "제어판.lnk", extension: "lnk", isDirectory: false, isShortcut: true, sizeBytes: 2_100, modifiedAt: day(500) }),
  entry({ name: "카카오톡.lnk", extension: "lnk", isDirectory: false, isShortcut: true, sizeBytes: 2_300, modifiedAt: day(120) }),
  entry({ name: "Visual Studio 2022.lnk", extension: "lnk", isDirectory: false, isShortcut: true, sizeBytes: 2_050, modifiedAt: day(200) }),
  entry({ name: "import_math.py", extension: "py", isDirectory: false, isShortcut: false, sizeBytes: 1_400, modifiedAt: day(30) }),
  entry({ name: "ALT_발표자료_초안.pdf", extension: "pdf", isDirectory: false, isShortcut: false, sizeBytes: 3_120_000, modifiedAt: day(45) }),
  entry({ name: "ALT_발표자료_최종.pdf", extension: "pdf", isDirectory: false, isShortcut: false, sizeBytes: 3_400_000, modifiedAt: day(12) }),
  entry({ name: "KakaoTalk_20260110_image.pdf", extension: "pdf", isDirectory: false, isShortcut: false, sizeBytes: 512_000, modifiedAt: day(8) }),
  entry({ name: "Food Sharing Platform UI", extension: "", isDirectory: true, isShortcut: false, sizeBytes: 0, modifiedAt: day(60) }),
  entry({ name: "Food Sharing Platform UI 기획서.pdf", extension: "pdf", isDirectory: false, isShortcut: false, sizeBytes: 2_800_000, modifiedAt: day(58) }),
  entry({ name: "권이유심_정리.pdf", extension: "pdf", isDirectory: false, isShortcut: false, sizeBytes: 220_000, modifiedAt: day(300) }),
  entry({ name: "tayo", extension: "", isDirectory: true, isShortcut: false, sizeBytes: 0, modifiedAt: day(90) }),
  entry({ name: "휴지통.lnk", extension: "lnk", isDirectory: false, isShortcut: true, sizeBytes: 1_800, modifiedAt: day(600) }),
  entry({ name: "반디집.lnk", extension: "lnk", isDirectory: false, isShortcut: true, sizeBytes: 2_000, modifiedAt: day(500) }),
  entry({ name: "Galaxy Book Members.lnk", extension: "lnk", isDirectory: false, isShortcut: true, sizeBytes: 2_000, modifiedAt: day(500) }),
  entry({ name: "다운로드 홈.lnk", extension: "lnk", isDirectory: false, isShortcut: true, sizeBytes: 1_900, modifiedAt: day(500) }),
  entry({ name: "9장_매개변수전달.pdf", extension: "pdf", isDirectory: false, isShortcut: false, sizeBytes: 640_000, modifiedAt: day(210) }),
  entry({ name: "ALT_최종보고서.pdf", extension: "pdf", isDirectory: false, isShortcut: false, sizeBytes: 4_100_000, modifiedAt: day(11) }),
  entry({ name: "ChatGPT Image 20260305.pdf", extension: "pdf", isDirectory: false, isShortcut: false, sizeBytes: 980_000, modifiedAt: day(20) }),
  entry({ name: "260312_03월12일(대추).pdf", extension: "pdf", isDirectory: false, isShortcut: false, sizeBytes: 150_000, modifiedAt: day(190) }),
  entry({ name: "자리잇다_사업계획서.xlsx", extension: "xlsx", isDirectory: false, isShortcut: false, sizeBytes: 88_000, modifiedAt: day(15) }),
  entry({ name: "tieakfjdskf", extension: "", isDirectory: true, isShortcut: false, sizeBytes: 0, modifiedAt: day(700) }),
  entry({ name: "meetpick", extension: "", isDirectory: true, isShortcut: false, sizeBytes: 0, modifiedAt: day(80) }),
  entry({ name: "외부정렬과제_보고서.hwpx", extension: "hwpx", isDirectory: false, isShortcut: false, sizeBytes: 310_000, modifiedAt: day(40) }),
  entry({ name: "바탕화면 - 바로가기.lnk", extension: "lnk", isDirectory: false, isShortcut: true, sizeBytes: 1_700, modifiedAt: day(500) }),
  entry({ name: "내 PC.lnk", extension: "lnk", isDirectory: false, isShortcut: true, sizeBytes: 1_700, modifiedAt: day(600) }),
  entry({ name: "EXCEL.lnk", extension: "lnk", isDirectory: false, isShortcut: true, sizeBytes: 1_600, modifiedAt: day(600) }),
  entry({ name: "GitHub Desktop.lnk", extension: "lnk", isDirectory: false, isShortcut: true, sizeBytes: 1_900, modifiedAt: day(300) }),
  entry({ name: "12장.pdf", extension: "pdf", isDirectory: false, isShortcut: false, sizeBytes: 580_000, modifiedAt: day(210) }),
  entry({ name: "6월2일_투두리스트_회의록.pdf", extension: "pdf", isDirectory: false, isShortcut: false, sizeBytes: 92_000, modifiedAt: day(110) }),
  entry({ name: "유주영_워크샵_자료.hwpx", extension: "hwpx", isDirectory: false, isShortcut: false, sizeBytes: 240_000, modifiedAt: day(70) }),
  entry({ name: "프레젠테이션1.pptx", extension: "pptx", isDirectory: false, isShortcut: false, sizeBytes: 5_600_000, modifiedAt: day(25) }),
  entry({ name: "사업기획서_최종.hwpx", extension: "hwpx", isDirectory: false, isShortcut: false, sizeBytes: 410_000, modifiedAt: day(9) }),
  entry({ name: "ml_mock_exam.pdf", extension: "pdf", isDirectory: false, isShortcut: false, sizeBytes: 720_000, modifiedAt: day(130) }),
  entry({ name: "ppt 레퍼런스", extension: "", isDirectory: true, isShortcut: false, sizeBytes: 0, modifiedAt: day(160) }),
  entry({ name: "외부정렬과제", extension: "", isDirectory: true, isShortcut: false, sizeBytes: 0, modifiedAt: day(41) }),
  entry({ name: "한워드 2024.lnk", extension: "lnk", isDirectory: false, isShortcut: true, sizeBytes: 1_500, modifiedAt: day(600) }),
  entry({ name: "꿀부.lnk", extension: "lnk", isDirectory: false, isShortcut: true, sizeBytes: 1_500, modifiedAt: day(600) }),
  entry({ name: "조교_매뉴얼.hwpx", extension: "hwpx", isDirectory: false, isShortcut: false, sizeBytes: 660_000, modifiedAt: day(230) }),
  entry({ name: "muscima-manual.pdf", extension: "pdf", isDirectory: false, isShortcut: false, sizeBytes: 1_200_000, modifiedAt: day(400) }),
  entry({ name: "통합 문서1.xlsx", extension: "xlsx", isDirectory: false, isShortcut: false, sizeBytes: 44_000, modifiedAt: day(5) }),
  entry({ name: "tkfkdgo.hwpx", extension: "hwpx", isDirectory: false, isShortcut: false, sizeBytes: 90_000, modifiedAt: day(650) }),
  entry({ name: "유주영_워크샵_참가신청서.pdf", extension: "pdf", isDirectory: false, isShortcut: false, sizeBytes: 130_000, modifiedAt: day(72) }),
  entry({ name: "TAYO.pptx", extension: "pptx", isDirectory: false, isShortcut: false, sizeBytes: 8_900_000, modifiedAt: day(33) }),
  entry({ name: "TAYO_PRD_최종.pptx", extension: "pptx", isDirectory: false, isShortcut: false, sizeBytes: 9_100_000, modifiedAt: day(6) }),
  entry({ name: "dream", extension: "", isDirectory: true, isShortcut: false, sizeBytes: 0, modifiedAt: day(140) }),
  entry({ name: "상장 및 증빙", extension: "", isDirectory: true, isShortcut: false, sizeBytes: 0, modifiedAt: day(280) }),
  entry({ name: "새 폴더", extension: "", isDirectory: true, isShortcut: false, sizeBytes: 0, modifiedAt: day(2) }),
  entry({ name: "한쇼 2024.lnk", extension: "lnk", isDirectory: false, isShortcut: true, sizeBytes: 1_600, modifiedAt: day(600) }),
  entry({ name: "WINWORD.lnk", extension: "lnk", isDirectory: false, isShortcut: true, sizeBytes: 1_600, modifiedAt: day(600) }),
  entry({ name: "투굿투고.pdf", extension: "pdf", isDirectory: false, isShortcut: false, sizeBytes: 260_000, modifiedAt: day(95) }),
  entry({ name: "김민관T.pptx", extension: "pptx", isDirectory: false, isShortcut: false, sizeBytes: 3_300_000, modifiedAt: day(180) }),
  entry({ name: "꿈청", extension: "", isDirectory: true, isShortcut: false, sizeBytes: 0, modifiedAt: day(260) }),
  entry({ name: "JH_참가신청서.pdf", extension: "pdf", isDirectory: false, isShortcut: false, sizeBytes: 140_000, modifiedAt: day(300) }),
  entry({ name: "LG aimers", extension: "", isDirectory: true, isShortcut: false, sizeBytes: 0, modifiedAt: day(150) }),
  entry({ name: "유주영_참가확인서 - 복사본.pdf", extension: "pdf", isDirectory: false, isShortcut: false, sizeBytes: 130_000, modifiedAt: day(72) }),
  entry({ name: "유주영_참가확인서.pdf", extension: "pdf", isDirectory: false, isShortcut: false, sizeBytes: 130_000, modifiedAt: day(72) }),
  entry({ name: "한셀 2024.lnk", extension: "lnk", isDirectory: false, isShortcut: true, sizeBytes: 1_600, modifiedAt: day(600) }),
  entry({ name: "User_guide.pdf", extension: "pdf", isDirectory: false, isShortcut: false, sizeBytes: 900_000, modifiedAt: day(500) }),
  entry({ name: "주영", extension: "", isDirectory: true, isShortcut: false, sizeBytes: 0, modifiedAt: day(310) }),
  entry({ name: "train", extension: "", isDirectory: true, isShortcut: false, sizeBytes: 0, modifiedAt: day(220) }),
  entry({ name: "OIBC", extension: "", isDirectory: true, isShortcut: false, sizeBytes: 0, modifiedAt: day(170) }),
  entry({ name: "KakaoTalk_20260220_meeting.pptx", extension: "pptx", isDirectory: false, isShortcut: false, sizeBytes: 2_200_000, modifiedAt: day(50) }),
  entry({ name: "멘토링_보고서.hwp", extension: "hwp", isDirectory: false, isShortcut: false, sizeBytes: 310_000, modifiedAt: day(19) }),
  entry({ name: "[일부미완성]멘토링_보고서.txt", extension: "txt", isDirectory: false, isShortcut: false, sizeBytes: 4_000, modifiedAt: day(19) }),
  entry({ name: "birthday_memo.txt", extension: "txt", isDirectory: false, isShortcut: false, sizeBytes: 2_000, modifiedAt: day(900) }),
  entry({ name: "프로젝트정리", extension: "", isDirectory: true, isShortcut: false, sizeBytes: 0, modifiedAt: day(100) }),
  entry({ name: "ezPDF Editor.lnk", extension: "lnk", isDirectory: false, isShortcut: true, sizeBytes: 1_700, modifiedAt: day(600) }),
  entry({ name: "한글 2024.lnk", extension: "lnk", isDirectory: false, isShortcut: true, sizeBytes: 1_700, modifiedAt: day(600) }),
  entry({ name: "WebCatalog.lnk", extension: "lnk", isDirectory: false, isShortcut: true, sizeBytes: 1_700, modifiedAt: day(600) }),
  entry({ name: "교재", extension: "", isDirectory: true, isShortcut: false, sizeBytes: 0, modifiedAt: day(250) }),
  entry({ name: "Visual Studio Code.lnk", extension: "lnk", isDirectory: false, isShortcut: true, sizeBytes: 1_700, modifiedAt: day(300) }),
  entry({ name: "ds_stack_queue.pdf", extension: "pdf", isDirectory: false, isShortcut: false, sizeBytes: 480_000, modifiedAt: day(240) }),
  entry({ name: "유주영_워크샵_교통비영수증.pdf", extension: "pdf", isDirectory: false, isShortcut: false, sizeBytes: 60_000, modifiedAt: day(71) }),
  entry({ name: "httpssonmun_scrap.txt", extension: "txt", isDirectory: false, isShortcut: false, sizeBytes: 8_000, modifiedAt: day(500) }),
  entry({ name: "아무거나넣어봄.txt", extension: "txt", isDirectory: false, isShortcut: false, sizeBytes: 1_200, modifiedAt: day(3) }),
  entry({ name: "한PDF 2024.lnk", extension: "lnk", isDirectory: false, isShortcut: true, sizeBytes: 1_700, modifiedAt: day(600) }),
  entry({ name: "POWERPNT.lnk", extension: "lnk", isDirectory: false, isShortcut: true, sizeBytes: 1_700, modifiedAt: day(600) }),
  entry({ name: "todo mate.lnk", extension: "lnk", isDirectory: false, isShortcut: true, sizeBytes: 1_700, modifiedAt: day(300) }),
  entry({ name: "Netflix.lnk", extension: "lnk", isDirectory: false, isShortcut: true, sizeBytes: 1_700, modifiedAt: day(600) }),
  entry({ name: "ViewItinerary.pdf", extension: "pdf", isDirectory: false, isShortcut: false, sizeBytes: 200_000, modifiedAt: day(400) }),
  entry({ name: "폴더", extension: "", isDirectory: true, isShortcut: false, sizeBytes: 0, modifiedAt: day(700) }),
  entry({ name: "유주영_증명.jpg", extension: "jpg", isDirectory: false, isShortcut: false, sizeBytes: 3_400_000, modifiedAt: day(72) }),
  entry({ name: "26.02.pdf", extension: "pdf", isDirectory: false, isShortcut: false, sizeBytes: 90_000, modifiedAt: day(60) }),
  entry({ name: "dream-chungju.pptx", extension: "pptx", isDirectory: false, isShortcut: false, sizeBytes: 4_400_000, modifiedAt: day(141) }),
  entry({ name: "2학년 2학기", extension: "", isDirectory: true, isShortcut: false, sizeBytes: 0, modifiedAt: day(320) }),
  entry({ name: "팟플레이어 64비트.lnk", extension: "lnk", isDirectory: false, isShortcut: true, sizeBytes: 1_700, modifiedAt: day(600) }),
  entry({ name: "개인 - Edge.lnk", extension: "lnk", isDirectory: false, isShortcut: true, sizeBytes: 1_700, modifiedAt: day(600) }),
  entry({ name: "기말.pdf", extension: "pdf", isDirectory: false, isShortcut: false, sizeBytes: 640_000, modifiedAt: day(210) }),
  entry({ name: "벡터.pdf", extension: "pdf", isDirectory: false, isShortcut: false, sizeBytes: 260_000, modifiedAt: day(240) }),
  entry({ name: "ChatGPT.lnk", extension: "lnk", isDirectory: false, isShortcut: true, sizeBytes: 1_700, modifiedAt: day(400) }),
  entry({ name: "260306_03월06일(공통).pdf", extension: "pdf", isDirectory: false, isShortcut: false, sizeBytes: 150_000, modifiedAt: day(196) }),
  entry({ name: "Document Print.pdf", extension: "pdf", isDirectory: false, isShortcut: false, sizeBytes: 200_000, modifiedAt: day(400) }),
  entry({ name: "사용자 기반 시스템.hwpx", extension: "hwpx", isDirectory: false, isShortcut: false, sizeBytes: 350_000, modifiedAt: day(150) }),
  entry({ name: "dream.zip", extension: "zip", isDirectory: false, isShortcut: false, sizeBytes: 12_000_000, modifiedAt: day(140) }),
  entry({ name: "운면.hwpx", extension: "hwpx", isDirectory: false, isShortcut: false, sizeBytes: 90_000, modifiedAt: day(950) }),
  entry({ name: "Google Chrome.lnk", extension: "lnk", isDirectory: false, isShortcut: true, sizeBytes: 1_700, modifiedAt: day(600) }),
  entry({ name: "클로바노트.lnk", extension: "lnk", isDirectory: false, isShortcut: true, sizeBytes: 1_700, modifiedAt: day(400) }),
  entry({ name: "ml_ch2_exam.pdf", extension: "pdf", isDirectory: false, isShortcut: false, sizeBytes: 380_000, modifiedAt: day(260) }),
  entry({ name: "XamVer.lnk", extension: "lnk", isDirectory: false, isShortcut: true, sizeBytes: 1_700, modifiedAt: day(600) }),
  entry({ name: "U300 수정본-보경 (1).docx", extension: "docx", isDirectory: false, isShortcut: false, sizeBytes: 220_000, modifiedAt: day(90) }),
  entry({ name: "Zoom Workplace.lnk", extension: "lnk", isDirectory: false, isShortcut: true, sizeBytes: 1_700, modifiedAt: day(600) }),
  entry({ name: "Melon Player.lnk", extension: "lnk", isDirectory: false, isShortcut: true, sizeBytes: 1_700, modifiedAt: day(600) }),
  entry({ name: "Cursor.lnk", extension: "lnk", isDirectory: false, isShortcut: true, sizeBytes: 1_700, modifiedAt: day(200) }),
  entry({ name: "setup_installer.exe", extension: "exe", isDirectory: false, isShortcut: false, sizeBytes: 45_000_000, modifiedAt: day(500) }),
];
